# Generated by Django 4.2.30 on 2026-06-16 00:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TimelineEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                ("titulo", models.CharField(max_length=255, verbose_name="Título")),
                ("descricao", models.TextField(blank=True, verbose_name="Descrição")),
                ("data_evento", models.DateField(verbose_name="Data do evento")),
                (
                    "data_precisao",
                    models.CharField(
                        choices=[
                            ("dia", "Dia exato"),
                            ("mes", "Mês"),
                            ("ano", "Ano"),
                            ("decada", "Década"),
                            ("seculo", "Século"),
                            ("desconhecida", "Desconhecida"),
                        ],
                        default="dia",
                        max_length=20,
                        verbose_name="Precisão da data",
                    ),
                ),
                (
                    "imagem_destaque",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="timeline/%Y/%m/",
                        verbose_name="Imagem de destaque",
                    ),
                ),
                (
                    "destaque",
                    models.BooleanField(default=False, verbose_name="Destaque"),
                ),
                ("ordem", models.PositiveIntegerField(default=0, verbose_name="Ordem")),
            ],
            options={
                "verbose_name": "Evento da linha do tempo",
                "verbose_name_plural": "Eventos da linha do tempo",
                "ordering": ["data_evento", "ordem", "-created_at"],
            },
        ),
    ]
