# Generated by Django 4.2.30 on 2026-06-27 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timeline", "0002_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="timelineevent",
            index=models.Index(
                fields=["data_evento", "ordem", "-created_at"],
                name="timeline_event_order_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="timelineevent",
            index=models.Index(fields=["destaque"], name="timeline_event_destaque_idx"),
        ),
        migrations.AddIndex(
            model_name="timelineevent",
            index=models.Index(
                fields=["documento"], name="timeline_event_documento_idx"
            ),
        ),
    ]
