# Generated by Django 4.2.30 on 2026-06-27 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0002_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="categoria",
            index=models.Index(
                fields=["ordem", "nome"], name="categoria_ordem_nome_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="categoria",
            index=models.Index(fields=["ativo"], name="categoria_ativo_idx"),
        ),
        migrations.AddIndex(
            model_name="categoria",
            index=models.Index(fields=["parent"], name="categoria_parent_idx"),
        ),
    ]
