# Generated by Django 4.2.30 on 2026-07-15 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_privacyrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_token_version',
            field=models.PositiveIntegerField(default=0, help_text='Incrementada para revogar imediatamente todas as sessões ativas.', verbose_name='Versão dos tokens de autenticação'),
        ),
        migrations.CreateModel(
            name='TwoFactorRecoveryCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo_hash', models.CharField(max_length=256, verbose_name='Hash do código')),
                ('usado_em', models.DateTimeField(blank=True, null=True, verbose_name='Usado em')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='twofactor_recovery_codes', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Código de recuperação 2FA',
                'verbose_name_plural': 'Códigos de recuperação 2FA',
                'ordering': ['criado_em'],
                'indexes': [models.Index(fields=['usuario', 'usado_em'], name='twofactor_recovery_active_idx')],
            },
        ),
    ]
