# Generated by Django 4.2.30 on 2026-07-15 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_auth_token_version_twofactorrecoverycode'),
    ]

    operations = [
        migrations.AddField(
            model_name='privacyrequest',
            name='base_legal',
            field=models.CharField(blank=True, max_length=160, verbose_name='Base legal'),
        ),
        migrations.AddField(
            model_name='privacyrequest',
            name='decisao_motivo',
            field=models.TextField(blank=True, verbose_name='Motivo da decisão'),
        ),
        migrations.AddField(
            model_name='privacyrequest',
            name='prazo_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Prazo interno'),
        ),
        migrations.AddField(
            model_name='privacyrequest',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='privacy_requests_assigned', to=settings.AUTH_USER_MODEL, verbose_name='Responsável'),
        ),
    ]
