# Generated by Django 4.2.30 on 2026-06-16 00:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProducaoAcademica",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                ("titulo", models.CharField(max_length=500, verbose_name="Título")),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("tcc", "TCC"),
                            ("dissertacao", "Dissertação"),
                            ("tese", "Tese"),
                            ("artigo", "Artigo"),
                            ("livro", "Livro"),
                            ("capitulo", "Capítulo de livro"),
                            ("outro", "Outro"),
                        ],
                        default="outro",
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                ("autor", models.CharField(max_length=255, verbose_name="Autor")),
                (
                    "orientador",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Orientador"
                    ),
                ),
                ("ano", models.PositiveIntegerField(verbose_name="Ano")),
                ("resumo", models.TextField(blank=True, verbose_name="Resumo")),
                (
                    "palavras_chave",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Palavras-chave"
                    ),
                ),
                (
                    "url_acesso",
                    models.URLField(blank=True, verbose_name="URL de acesso"),
                ),
                (
                    "citacao_abnt",
                    models.TextField(blank=True, verbose_name="Citação ABNT"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=500, unique=True, verbose_name="Slug"
                    ),
                ),
            ],
            options={
                "verbose_name": "Produção acadêmica",
                "verbose_name_plural": "Produções acadêmicas",
                "ordering": ["-ano", "titulo"],
            },
        ),
    ]
