# Generated by Django 4.2.30 on 2026-06-16 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("documents", "0001_initial"),
        ("academic", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="producaoacademica",
            name="arquivo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="producoes_academicas",
                to="documents.arquivo",
                verbose_name="Arquivo",
            ),
        ),
    ]
