# Generated by Django 4.2.30 on 2026-06-27 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0003_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="producaoacademica",
            index=models.Index(
                fields=["-ano", "titulo"], name="producao_ano_titulo_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="producaoacademica",
            index=models.Index(
                fields=["tipo", "ativo"], name="producao_tipo_ativo_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="producaoacademica",
            index=models.Index(fields=["slug"], name="producao_slug_idx"),
        ),
    ]
