# Generated by Django 4.2.30 on 2026-06-16 00:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Auditoria",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "acao",
                    models.CharField(
                        choices=[
                            ("criar", "Criar"),
                            ("atualizar", "Atualizar"),
                            ("excluir", "Excluir"),
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("aprovar", "Aprovar"),
                            ("rejeitar", "Rejeitar"),
                            ("submeter", "Submeter"),
                            ("arquivar", "Arquivar"),
                        ],
                        max_length=20,
                        verbose_name="Ação",
                    ),
                ),
                ("entidade", models.CharField(max_length=100, verbose_name="Entidade")),
                (
                    "entidade_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ID da entidade"
                    ),
                ),
                (
                    "dados_anteriores",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Dados anteriores"
                    ),
                ),
                (
                    "dados_novos",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Dados novos"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Endereço IP"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User-Agent")),
            ],
            options={
                "verbose_name": "Auditoria",
                "verbose_name_plural": "Auditorias",
                "ordering": ["-created_at"],
            },
        ),
    ]
