# Generated by Django 4.2.30 on 2026-06-27 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0002_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="album",
            index=models.Index(
                fields=["-destaque", "-created_at"], name="album_destaque_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="foto",
            index=models.Index(
                fields=["album", "ordem", "created_at"], name="foto_album_ordem_idx"
            ),
        ),
    ]
