# Generated by Django 4.2.30 on 2026-06-27 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0002_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="tag",
            index=models.Index(fields=["nome"], name="tag_nome_idx"),
        ),
    ]
