# Generated by Django 4.2.30 on 2026-06-16 00:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Arquivo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "nome_original",
                    models.CharField(max_length=500, verbose_name="Nome original"),
                ),
                (
                    "nome_armazenado",
                    models.CharField(max_length=500, verbose_name="Nome armazenado"),
                ),
                (
                    "arquivo",
                    models.FileField(
                        upload_to="documentos/%Y/%m/", verbose_name="Arquivo"
                    ),
                ),
                (
                    "mime_type",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Tipo MIME"
                    ),
                ),
                (
                    "tamanho_bytes",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="Tamanho em bytes"
                    ),
                ),
                (
                    "checksum_sha256",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Checksum SHA-256"
                    ),
                ),
                (
                    "largura",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Largura"
                    ),
                ),
                (
                    "altura",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Altura"
                    ),
                ),
                (
                    "tipo_arquivo",
                    models.CharField(
                        choices=[
                            ("original", "Original"),
                            ("thumbnail", "Thumbnail"),
                            ("ocr_text", "Texto OCR"),
                            ("watermark", "Marca d'água"),
                        ],
                        default="original",
                        max_length=20,
                        verbose_name="Tipo de arquivo",
                    ),
                ),
                (
                    "processado_ocr",
                    models.BooleanField(default=False, verbose_name="Processado OCR"),
                ),
                (
                    "conteudo_ocr",
                    models.TextField(blank=True, verbose_name="Conteúdo OCR"),
                ),
            ],
            options={
                "verbose_name": "Arquivo",
                "verbose_name_plural": "Arquivos",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Autor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                ("nome", models.CharField(max_length=255, verbose_name="Nome")),
                ("biografia", models.TextField(blank=True, verbose_name="Biografia")),
                (
                    "data_nascimento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de nascimento"
                    ),
                ),
                (
                    "data_falecimento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de falecimento"
                    ),
                ),
            ],
            options={
                "verbose_name": "Autor",
                "verbose_name_plural": "Autores",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                ("titulo", models.CharField(max_length=500, verbose_name="Título")),
                (
                    "titulo_alternativo",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Título alternativo"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=500, unique=True, verbose_name="Slug"),
                ),
                ("descricao", models.TextField(blank=True, verbose_name="Descrição")),
                ("resumo", models.TextField(blank=True, verbose_name="Resumo")),
                (
                    "codigo_referencia",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Código de referência"
                    ),
                ),
                (
                    "tipo_documento",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Tipo de documento"
                    ),
                ),
                (
                    "data_documento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data do documento"
                    ),
                ),
                (
                    "data_precisao",
                    models.CharField(
                        choices=[
                            ("dia", "Dia exato"),
                            ("mes", "Mês"),
                            ("ano", "Ano"),
                            ("decada", "Década"),
                            ("seculo", "Século"),
                            ("desconhecida", "Desconhecida"),
                        ],
                        default="desconhecida",
                        max_length=20,
                        verbose_name="Precisão da data",
                    ),
                ),
                (
                    "cobertura_temporal",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Cobertura temporal"
                    ),
                ),
                (
                    "cobertura_espacial",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Cobertura espacial"
                    ),
                ),
                (
                    "idioma",
                    models.CharField(
                        default="pt-BR", max_length=50, verbose_name="Idioma"
                    ),
                ),
                ("direitos", models.TextField(blank=True, verbose_name="Direitos")),
                (
                    "fonte",
                    models.CharField(blank=True, max_length=500, verbose_name="Fonte"),
                ),
                (
                    "relacao",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Relação"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("rascunho", "Rascunho"),
                            ("em_revisao", "Em revisão"),
                            ("aprovado", "Aprovado"),
                            ("rejeitado", "Rejeitado"),
                            ("publicado", "Publicado"),
                            ("arquivado", "Arquivado"),
                        ],
                        default="rascunho",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "data_aprovacao",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data de aprovação"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Excluído em"
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento",
                "verbose_name_plural": "Documentos",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentoAutor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "tipo_autoria",
                    models.CharField(
                        default="autor", max_length=100, verbose_name="Tipo de autoria"
                    ),
                ),
            ],
            options={
                "verbose_name": "Autoria",
                "verbose_name_plural": "Autorias",
            },
        ),
        migrations.CreateModel(
            name="DocumentoCategoria",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Vínculo categoria",
                "verbose_name_plural": "Vínculos categoria",
            },
        ),
        migrations.CreateModel(
            name="DocumentoRelacionado",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "tipo_relacao",
                    models.CharField(
                        default="relacionado",
                        max_length=100,
                        verbose_name="Tipo de relação",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento relacionado",
                "verbose_name_plural": "Documentos relacionados",
            },
        ),
        migrations.CreateModel(
            name="DocumentoTag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Vínculo tag",
                "verbose_name_plural": "Vínculos tag",
            },
        ),
    ]
