# Generated by Django 4.2.30 on 2026-06-16 00:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("documents", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tags", "0001_initial"),
        ("categories", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentotag",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Criado por",
            ),
        ),
        migrations.AddField(
            model_name="documentotag",
            name="documento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documento_tags",
                to="documents.document",
                verbose_name="Documento",
            ),
        ),
        migrations.AddField(
            model_name="documentotag",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tag_documentos",
                to="tags.tag",
                verbose_name="Tag",
            ),
        ),
        migrations.AddField(
            model_name="documentorelacionado",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Criado por",
            ),
        ),
        migrations.AddField(
            model_name="documentorelacionado",
            name="documento_destino",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="relacionamentos_destino",
                to="documents.document",
                verbose_name="Documento relacionado",
            ),
        ),
        migrations.AddField(
            model_name="documentorelacionado",
            name="documento_origem",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="relacionamentos_origem",
                to="documents.document",
                verbose_name="Documento de origem",
            ),
        ),
        migrations.AddField(
            model_name="documentocategoria",
            name="categoria",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categoria_documentos",
                to="categories.categoria",
                verbose_name="Categoria",
            ),
        ),
        migrations.AddField(
            model_name="documentocategoria",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Criado por",
            ),
        ),
        migrations.AddField(
            model_name="documentocategoria",
            name="documento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documento_categorias",
                to="documents.document",
                verbose_name="Documento",
            ),
        ),
        migrations.AddField(
            model_name="documentoautor",
            name="autor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="autor_documentos",
                to="documents.autor",
                verbose_name="Autor",
            ),
        ),
        migrations.AddField(
            model_name="documentoautor",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Criado por",
            ),
        ),
        migrations.AddField(
            model_name="documentoautor",
            name="documento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documento_autores",
                to="documents.document",
                verbose_name="Documento",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="aprovado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documentos_aprovados",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Aprovado por",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="autores",
            field=models.ManyToManyField(
                related_name="documentos",
                through="documents.DocumentoAutor",
                to="documents.autor",
                verbose_name="Autores",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="categorias",
            field=models.ManyToManyField(
                related_name="documentos",
                through="documents.DocumentoCategoria",
                to="categories.categoria",
                verbose_name="Categorias",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Criado por",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="tags",
            field=models.ManyToManyField(
                related_name="documentos",
                through="documents.DocumentoTag",
                to="tags.tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AddField(
            model_name="autor",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Criado por",
            ),
        ),
        migrations.AddField(
            model_name="arquivo",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Criado por",
            ),
        ),
        migrations.AddField(
            model_name="arquivo",
            name="documento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="arquivos",
                to="documents.document",
                verbose_name="Documento",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="documentotag",
            unique_together={("documento", "tag")},
        ),
        migrations.AlterUniqueTogether(
            name="documentorelacionado",
            unique_together={("documento_origem", "documento_destino", "tipo_relacao")},
        ),
        migrations.AlterUniqueTogether(
            name="documentocategoria",
            unique_together={("documento", "categoria")},
        ),
        migrations.AlterUniqueTogether(
            name="documentoautor",
            unique_together={("documento", "autor", "tipo_autoria")},
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["status", "deleted_at"], name="documents_d_status_52b1a4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(fields=["slug"], name="documents_d_slug_3df491_idx"),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["tipo_documento"], name="documents_d_tipo_do_35a107_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["data_documento"], name="documents_d_data_do_ab945d_idx"
            ),
        ),
    ]
