# Generated by Django 4.2.30 on 2026-06-26 19:36

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0003_fts_search_vector"),
    ]

    operations = [
        migrations.AlterField(
            model_name="arquivo",
            name="arquivo",
            field=models.FileField(
                upload_to="documentos/%Y/%m/",
                validators=[apps.core.validators.validate_upload],
                verbose_name="Arquivo",
            ),
        ),
    ]
