# Generated by Django 4.2.30 on 2026-06-27 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0005_document_motivo_rejeicao"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="document",
            name="documents_d_status_52b1a4_idx",
        ),
        migrations.AddIndex(
            model_name="arquivo",
            index=models.Index(
                fields=["documento", "tipo_arquivo"], name="arquivo_doc_tipo_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="autor",
            index=models.Index(fields=["nome"], name="autor_nome_idx"),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["status", "deleted_at", "-created_at"],
                name="documents_pub_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="documentorelacionado",
            index=models.Index(fields=["documento_origem"], name="doc_rel_origem_idx"),
        ),
    ]
