# Generated by Django 4.2.30 on 2026-07-15 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_arquivo_processing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivo',
            name='antivirus_diagnostico',
            field=models.CharField(blank=True, max_length=500, verbose_name='Diagnóstico do antivírus'),
        ),
        migrations.AddField(
            model_name='arquivo',
            name='antivirus_escaneado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Escaneado em'),
        ),
        migrations.AddField(
            model_name='arquivo',
            name='antivirus_status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('escaneando', 'Escaneando'), ('limpo', 'Limpo'), ('infectado', 'Infectado'), ('indisponivel', 'Indisponível'), ('ignorado', 'Ignorado')], default='pendente', max_length=20, verbose_name='Status do antivírus'),
        ),
    ]
